baseURL = "https://code-at-the-edge.github.io/"
languageCode = "en-us"
title = "KGBV Learns Code!"
theme = "docdock"

# ignoreFiles = [ "\\.css$", "\\.boo$" ]

# SYNTAX
# Highlighting config (Pygments)
pygmentsCodeFences = true
pygmentsOptions = ""

# Use the Chroma stylesheet
pygmentsUseClasses = true
pygmentsUseClassic = false

# See https://xyproto.github.io/splash/docs/all.html
pygmentsStyle = "monokailight"

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday

[blackfriday]
  angledQuotes = true
  extensions = ["hardLineBreak"]
